<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

		$countries = Array(
            array('id' => 1, 'code' => 'cm', 'name' => 'Cameroon'),
            array('id' => 2, 'code' => 'bj', 'name' => 'Benin'),
            array('id' => 3, 'code' => 'mg', 'name' => 'Madagascar'),
            array('id' => 4, 'code' => 'rw', 'name' => 'Rwanda'),
            array('id' => 5, 'code' => 'sc', 'name' => 'Seychelles'),
            array('id' => 6, 'code' => 'ci', 'name' => 'Cote d’Ivoire'),
            array('id' => 7, 'code' => 'eg', 'name' => 'Egypt'),
            array('id' => 8, 'code' => 'mu', 'name' => 'Mauritius'),
            array('id' => 9, 'code' => 'bf', 'name' => 'Burkina Faso'),
            array('id' => 10, 'code' => 'er', 'name' => 'Eritrea'),
            array('id' => 11, 'code' => 'st', 'name' => 'Sao Tome and Principe'),
            array('id' => 12, 'code' => 'ao', 'name' => 'Angola'),
            array('id' => 13, 'code' => 'ly', 'name' => 'Libya'),
            array('id' => 14, 'code' => 'zw', 'name' => 'Zimbabwe'),
            array('id' => 15, 'code' => 'gn', 'name' => 'Guinea'),
            array('id' => 16, 'code' => 'sl', 'name' => 'Sierra Leone'),
            array('id' => 17, 'code' => 're', 'name' => 'Reunion'),
            array('id' => 18, 'code' => 'ga', 'name' => 'Gabon'),
            array('id' => 19, 'code' => 'gh', 'name' => 'Ghana'),
            array('id' => 20, 'code' => 'tz', 'name' => 'Tanzania'),
            array('id' => 21, 'code' => 'ml', 'name' => 'Mali'),
            array('id' => 22, 'code' => 'so', 'name' => 'Somalia'),
            array('id' => 23, 'code' => 'mr', 'name' => 'Mauritania'),
            array('id' => 24, 'code' => 'ug', 'name' => 'Uganda'),
            array('id' => 25, 'code' => 'td', 'name' => 'Chad'),
            array('id' => 26, 'code' => 'yt', 'name' => 'Mayotte'),
            array('id' => 27, 'code' => 'km', 'name' => 'Comoros'),
            array('id' => 28, 'code' => 'bw', 'name' => 'Botswana'),
            array('id' => 29, 'code' => 'sn', 'name' => 'Senegal'),
            array('id' => 30, 'code' => 'sz', 'name' => 'Eswatini'),
            array('id' => 31, 'code' => 'gw', 'name' => 'Guinea-Bissau'),
            array('id' => 32, 'code' => 'cd', 'name' => 'DR Congo'),
            array('id' => 33, 'code' => 'cf', 'name' => 'Central African Republic'),
            array('id' => 34, 'code' => 'ls', 'name' => 'Lesotho'),
            array('id' => 35, 'code' => 'cg', 'name' => 'Congo'),
            array('id' => 36, 'code' => 'za', 'name' => 'South Africa'),
            array('id' => 37, 'code' => 'lr', 'name' => 'Liberia'),
            array('id' => 38, 'code' => 'tn', 'name' => 'Tunisia'),
            array('id' => 39, 'code' => 'zm', 'name' => 'Zambia'),
            array('id' => 40, 'code' => 'ne', 'name' => 'Niger'),
            array('id' => 41, 'code' => 'eh', 'name' => 'Western Sahara'),
            array('id' => 42, 'code' => 'tg', 'name' => 'Togo'),
            array('id' => 43, 'code' => 'na', 'name' => 'Namibia'),
            array('id' => 44, 'code' => 'mz', 'name' => 'Mozambique'),
            array('id' => 45, 'code' => 'et', 'name' => 'Ethiopia'),
            array('id' => 46, 'code' => 'ma', 'name' => 'Morocco'),
            array('id' => 47, 'code' => 'mw', 'name' => 'Malawi'),
            array('id' => 48, 'code' => 'ng', 'name' => 'Nigeria'),
            array('id' => 49, 'code' => 'cv', 'name' => 'Cabo Verde'),
            array('id' => 50, 'code' => 'bi', 'name' => 'Burundi'),
            array('id' => 51, 'code' => 'dz', 'name' => 'Algeria'),
            array('id' => 52, 'code' => 'dj', 'name' => 'Djibouti'),
            array('id' => 53, 'code' => 'gp', 'name' => 'Guadeloupe'),
            array('id' => 54, 'code' => 'gq', 'name' => 'Equatorial Guinea'),
            array('id' => 55, 'code' => 'sd', 'name' => 'Sudan'),
            array('id' => 56, 'code' => 'ke', 'name' => 'Kenya'),
            array('id' => 57, 'code' => 'sg', 'name' => 'Singapore'),
            array('id' => 58, 'code' => 'kr', 'name' => 'South Korea'),
            array('id' => 59, 'code' => 'sy', 'name' => 'Syria'),
            array('id' => 60, 'code' => 'uz', 'name' => 'Uzbekistan'),
            array('id' => 61, 'code' => 'bh', 'name' => 'Bahrain'),
            array('id' => 62, 'code' => 'jp', 'name' => 'Japan'),
            array('id' => 63, 'code' => 'jo', 'name' => 'Jordan'),
            array('id' => 64, 'code' => 'vn', 'name' => 'Vietnam'),
            array('id' => 65, 'code' => 'kg', 'name' => 'Kyrgyzstan'),
            array('id' => 66, 'code' => 'th', 'name' => 'Thailand'),
            array('id' => 67, 'code' => 'lk', 'name' => 'Sri Lanka'),
            array('id' => 68, 'code' => 'ae', 'name' => 'United Arab Emirates'),
            array('id' => 69, 'code' => 'la', 'name' => 'Laos'),
            array('id' => 70, 'code' => 'af', 'name' => 'Afghanistan'),
            array('id' => 71, 'code' => 'mo', 'name' => 'Macau'),
            array('id' => 72, 'code' => 'tj', 'name' => 'Tajikistan'),
            array('id' => 73, 'code' => 'kp', 'name' => 'North Korea'),
            array('id' => 74, 'code' => 'ps', 'name' => 'Palestine'),
            array('id' => 75, 'code' => 'hk', 'name' => 'Hong Kong'),
            array('id' => 76, 'code' => 'iq', 'name' => 'Iraq'),
            array('id' => 77, 'code' => 'lb', 'name' => 'Lebanon'),
            array('id' => 78, 'code' => 'kw', 'name' => 'Kuwait'),
            array('id' => 79, 'code' => 'bn', 'name' => 'Brunei'),
            array('id' => 80, 'code' => 'mv', 'name' => 'Maldives'),
            array('id' => 81, 'code' => 'id', 'name' => 'Indonesia'),
            array('id' => 82, 'code' => 'il', 'name' => 'Israel'),
            array('id' => 83, 'code' => 'mn', 'name' => 'Mongolia'),
            array('id' => 84, 'code' => 'om', 'name' => 'Oman'),
            array('id' => 85, 'code' => 'in', 'name' => 'India'),
            array('id' => 86, 'code' => 'mm', 'name' => 'Myanmar'),
            array('id' => 87, 'code' => 'my', 'name' => 'Malaysia'),
            array('id' => 88, 'code' => 'tl', 'name' => 'East Timor'),
            array('id' => 89, 'code' => 'ye', 'name' => 'Yemen'),
            array('id' => 90, 'code' => 'bt', 'name' => 'Bhutan'),
            array('id' => 91, 'code' => 'kh', 'name' => 'Cambodia'),
            array('id' => 92, 'code' => 'pk', 'name' => 'Pakistan'),
            array('id' => 93, 'code' => 'bd', 'name' => 'Bangladesh'),
            array('id' => 94, 'code' => 'sa', 'name' => 'Saudi Arabia'),
            array('id' => 95, 'code' => 'tm', 'name' => 'Turkmenistan'),
            array('id' => 96, 'code' => 'qa', 'name' => 'Qatar'),
            array('id' => 97, 'code' => 'np', 'name' => 'Nepal'),
            array('id' => 98, 'code' => 'kz', 'name' => 'Kazakhstan'),
            array('id' => 99, 'code' => 'ph', 'name' => 'Philippines'),
            array('id' => 100, 'code' => 'tw', 'name' => 'Taiwan'),
            array('id' => 101, 'code' => 'cn', 'name' => 'China'),
            array('id' => 102, 'code' => 'ir', 'name' => 'Iran'),
            array('id' => 103, 'code' => 'cr', 'name' => 'Costa Rica'),
            array('id' => 104, 'code' => 'cu', 'name' => 'Cuba'),
            array('id' => 105, 'code' => 'do', 'name' => 'Dominican'),
            array('id' => 106, 'code' => 'mx', 'name' => 'Mexico'),
            array('id' => 107, 'code' => 'ni', 'name' => 'Nicaragua'),
            array('id' => 108, 'code' => 'pa', 'name' => 'Panama'),
            array('id' => 109, 'code' => 'an', 'name' => 'Netherlands Antilles'),
            array('id' => 110, 'code' => 'sv', 'name' => 'El Salvador'),
            array('id' => 111, 'code' => 'pr', 'name' => 'Puerto Rico'),
            array('id' => 112, 'code' => 'vc', 'name' => 'Saint Vincent and the Grenadines'),
            array('id' => 113, 'code' => 'hn', 'name' => 'Honduras'),
            array('id' => 114, 'code' => 'gt', 'name' => 'Guatemala'),
            array('id' => 115, 'code' => 'ge', 'name' => 'Georgia'),
            array('id' => 116, 'code' => 'am', 'name' => 'Armenia'),
            array('id' => 117, 'code' => 'az', 'name' => 'Azerbaijan'),
            array('id' => 118, 'code' => 'by', 'name' => 'Belarus'),
            array('id' => 119, 'code' => 'ru', 'name' => 'Russia'),
            array('id' => 120, 'code' => 'ua', 'name' => 'Ukraine'),
            array('id' => 121, 'code' => 'hu', 'name' => 'Hungary'),
            array('id' => 122, 'code' => 'is', 'name' => 'Iceland'),
            array('id' => 123, 'code' => 'mt', 'name' => 'Malta'),
            array('id' => 124, 'code' => 'mc', 'name' => 'Monaco'),
            array('id' => 125, 'code' => 'no', 'name' => 'Norway'),
            array('id' => 126, 'code' => 'ro', 'name' => 'Romania'),
            array('id' => 127, 'code' => 'sm', 'name' => 'San Marino'),
            array('id' => 128, 'code' => 'se', 'name' => 'Sweden'),
            array('id' => 129, 'code' => 'ch', 'name' => 'Switzerland'),
            array('id' => 130, 'code' => 'ee', 'name' => 'Estonia'),
            array('id' => 131, 'code' => 'lv', 'name' => 'Latvia'),
            array('id' => 132, 'code' => 'lt', 'name' => 'Lithuania'),
            array('id' => 133, 'code' => 'md', 'name' => 'Moldova'),
            array('id' => 134, 'code' => 'tr', 'name' => 'Turkey'),
            array('id' => 135, 'code' => 'si', 'name' => 'Slovenia'),
            array('id' => 136, 'code' => 'cz', 'name' => 'Czech'),
            array('id' => 137, 'code' => 'sk', 'name' => 'Slovakia'),
            array('id' => 138, 'code' => 'mk', 'name' => 'North Macedonia'),
            array('id' => 139, 'code' => 'ba', 'name' => 'Bosnia Herzegovina'),
            array('id' => 140, 'code' => 'va', 'name' => 'Vatican City State'),
            array('id' => 141, 'code' => 'nl', 'name' => 'Netherlands'),
            array('id' => 142, 'code' => 'hr', 'name' => 'Croatia'),
            array('id' => 143, 'code' => 'gr', 'name' => 'Greece'),
            array('id' => 144, 'code' => 'ie', 'name' => 'Ireland'),
            array('id' => 145, 'code' => 'be', 'name' => 'Belgium'),
            array('id' => 146, 'code' => 'cy', 'name' => 'Cyprus'),
            array('id' => 147, 'code' => 'dk', 'name' => 'Denmark'),
            array('id' => 148, 'code' => 'gb', 'name' => 'United Kingdom'),
            array('id' => 149, 'code' => 'de', 'name' => 'Germany'),
            array('id' => 150, 'code' => 'fr', 'name' => 'France'),
            array('id' => 151, 'code' => 'it', 'name' => 'Italy'),
            array('id' => 152, 'code' => 'lu', 'name' => 'Luxembourg'),
            array('id' => 153, 'code' => 'pt', 'name' => 'Portugal'),
            array('id' => 154, 'code' => 'pl', 'name' => 'Poland'),
            array('id' => 155, 'code' => 'es', 'name' => 'Spain'),
            array('id' => 156, 'code' => 'al', 'name' => 'Albania'),
            array('id' => 157, 'code' => 'ad', 'name' => 'Andorra'),
            array('id' => 158, 'code' => 'li', 'name' => 'Liechtenstein'),
            array('id' => 159, 'code' => 'rs', 'name' => 'Serbia'),
            array('id' => 160, 'code' => 'at', 'name' => 'Austria'),
            array('id' => 161, 'code' => 'bg', 'name' => 'Bulgaria'),
            array('id' => 162, 'code' => 'fi', 'name' => 'Finland'),
            array('id' => 163, 'code' => 'gi', 'name' => 'Gibraltar'),
            array('id' => 164, 'code' => 'dm', 'name' => 'Dominica'),
            array('id' => 165, 'code' => 'bm', 'name' => 'Bermuda'),
            array('id' => 166, 'code' => 'ca', 'name' => 'Canada'),
            array('id' => 167, 'code' => 'us', 'name' => 'United States'),
            array('id' => 168, 'code' => 'gl', 'name' => 'Greenland'),
            array('id' => 169, 'code' => 'to', 'name' => 'Tonga'),
            array('id' => 170, 'code' => 'au', 'name' => 'Australia'),
            array('id' => 171, 'code' => 'ck', 'name' => 'Cook Islands'),
            array('id' => 172, 'code' => 'nr', 'name' => 'Nauru'),
            array('id' => 173, 'code' => 'nc', 'name' => 'New Caledonia'),
            array('id' => 174, 'code' => 'vu', 'name' => 'Vanuatu'),
            array('id' => 175, 'code' => 'sb', 'name' => 'Solomon Islands'),
            array('id' => 176, 'code' => 'ws', 'name' => 'Samoa'),
            array('id' => 177, 'code' => 'tv', 'name' => 'Tuvalu'),
            array('id' => 178, 'code' => 'fm', 'name' => 'Micronesia'),
            array('id' => 179, 'code' => 'mh', 'name' => 'Marshall Islands'),
            array('id' => 180, 'code' => 'ki', 'name' => 'Kiribati'),
            array('id' => 181, 'code' => 'pf', 'name' => 'French Polynesia'),
            array('id' => 182, 'code' => 'nz', 'name' => 'New Zealand'),
            array('id' => 183, 'code' => 'fj', 'name' => 'Fiji'),
            array('id' => 184, 'code' => 'pg', 'name' => 'Papua New Guinea'),
            array('id' => 185, 'code' => 'pw', 'name' => 'Palau'),
            array('id' => 186, 'code' => 'cl', 'name' => 'Chile'),
            array('id' => 187, 'code' => 'co', 'name' => 'Colombia'),
            array('id' => 188, 'code' => 'gy', 'name' => 'Guyana'),
            array('id' => 189, 'code' => 'py', 'name' => 'Paraguay'),
            array('id' => 190, 'code' => 'pe', 'name' => 'Peru'),
            array('id' => 191, 'code' => 'sr', 'name' => 'Suriname'),
            array('id' => 192, 'code' => 've', 'name' => 'Venezuela'),
            array('id' => 193, 'code' => 'uy', 'name' => 'Uruguay'),
            array('id' => 194, 'code' => 'ec', 'name' => 'Ecuador'),
            array('id' => 195, 'code' => 'ag', 'name' => 'Antigua and Barbuda'),
            array('id' => 196, 'code' => 'aw', 'name' => 'Aruba'),
            array('id' => 197, 'code' => 'bs', 'name' => 'Bahamas'),
            array('id' => 198, 'code' => 'bb', 'name' => 'Barbados'),
            array('id' => 199, 'code' => 'ky', 'name' => 'Cayman Islands'),
            array('id' => 200, 'code' => 'gd', 'name' => 'Grenada'),
            array('id' => 201, 'code' => 'ht', 'name' => 'Haiti'),
            array('id' => 202, 'code' => 'jm', 'name' => 'Jamaica'),
            array('id' => 203, 'code' => 'mq', 'name' => 'Martinique'),
            array('id' => 204, 'code' => 'ms', 'name' => 'Montserrat'),
            array('id' => 205, 'code' => 'tt', 'name' => 'Trinidad and Tobago'),
            array('id' => 206, 'code' => 'kn', 'name' => 'Saint Kitts and Nevis'),
            array('id' => 207, 'code' => 'pm', 'name' => 'Saint Pierre and Miquelon'),
            array('id' => 208, 'code' => 'ar', 'name' => 'Argentina'),
            array('id' => 209, 'code' => 'bz', 'name' => 'Belize'),
            array('id' => 210, 'code' => 'bo', 'name' => 'Bolivia'),
            array('id' => 211, 'code' => 'br', 'name' => 'Brazil'),
            array('id' => 212, 'code' => 'as', 'name' => 'American Samoa'),
            array('id' => 213, 'code' => 'ax', 'name' => 'Aland Islands'),
            array('id' => 214, 'code' => 'bl', 'name' => 'Saint Barthélemy'),
            array('id' => 215, 'code' => 'bq', 'name' => 'Bonaire, Sint Eustatius and Saba'),
            array('id' => 216, 'code' => 'bv', 'name' => 'Bouvet Island'),
            array('id' => 217, 'code' => 'cc', 'name' => 'Cocos (Keeling) Islands'),
            array('id' => 218, 'code' => 'cw', 'name' => 'Curaçao'),
            array('id' => 219, 'code' => 'cx', 'name' => 'Christmas Island'),
            array('id' => 220, 'code' => 'fk', 'name' => 'Falkland Islands (Malvinas)'),
            array('id' => 221, 'code' => 'fo', 'name' => 'Faroe Islands'),
            array('id' => 222, 'code' => 'gf', 'name' => 'French Guiana'),
            array('id' => 223, 'code' => 'gg', 'name' => 'Guernsey'),
            array('id' => 224, 'code' => 'gs', 'name' => 'South Georgia and the South Sandwich Islands'),
            array('id' => 225, 'code' => 'gu', 'name' => 'Guam'),
            array('id' => 226, 'code' => 'hm', 'name' => 'Heard Island and McDonald Islands'),
            array('id' => 227, 'code' => 'im', 'name' => 'Isle of Man'),
            array('id' => 228, 'code' => 'io', 'name' => 'British Indian Ocean Territory'),
            array('id' => 229, 'code' => 'je', 'name' => 'Jersey'),
            array('id' => 230, 'code' => 'lc', 'name' => 'Saint Lucia'),
            array('id' => 231, 'code' => 'mf', 'name' => 'Saint Martin'),
            array('id' => 232, 'code' => 'mp', 'name' => 'Northern Mariana Islands'),
            array('id' => 233, 'code' => 'nf', 'name' => 'Norfolk Island'),
            array('id' => 234, 'code' => 'nu', 'name' => 'Niue'),
            array('id' => 236, 'code' => 'pn', 'name' => 'Pitcairn'),
            array('id' => 237, 'code' => 'sh', 'name' => 'Saint Helena'),
            array('id' => 238, 'code' => 'sj', 'name' => 'Svalbard and Jan Mayen Islands'),
            array('id' => 239, 'code' => 'sx', 'name' => 'Sint Maarten'),
            array('id' => 240, 'code' => 'tc', 'name' => 'Turks and Caicos Islands'),
            array('id' => 241, 'code' => 'tf', 'name' => 'French Southern Territories'),
            array('id' => 242, 'code' => 'tk', 'name' => 'Tokelau'),
            array('id' => 243, 'code' => 'um', 'name' => 'United States Minor Outlying Islands'),
            array('id' => 244, 'code' => 'vg', 'name' => 'British Virgin Islands'),
            array('id' => 245, 'code' => 'vi', 'name' => 'United States Virgin Islands'),
            array('id' => 246, 'code' => 'wf', 'name' => 'Wallis and Futuna Islands'),
            array('id' => 247, 'code' => 'xk', 'name' => 'Kosovo'),
            array('id' => 248, 'code' => 'me', 'name' => 'Montenegro'),
            array('id' => 249, 'code' => 'ai', 'name' => 'Anguilla'),
            array('id' => 250, 'code' => 'gm', 'name' => 'Gambia'),
            array('id' => 251, 'code' => 'ss', 'name' => 'South Sudan'),
            );
		DB::table('countries')->insert($countries);
    }
}
